// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppRunning():Promise<boolean>;

export function CloseRunningApp():Promise<void>;

export function DetectState():Promise<main.StateDTO>;

export function Install(arg1:boolean):Promise<void>;

export function Quit():Promise<void>;

export function Repair():Promise<void>;

export function SetLaunchOnBoot(arg1:boolean):Promise<void>;

export function Uninstall(arg1:boolean):Promise<void>;
