// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectState() {
  return window['go']['main']['App']['DetectState']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Repair() {
  return window['go']['main']['App']['Repair']();
}

export function SetLaunchOnBoot(arg1) {
  return window['go']['main']['App']['SetLaunchOnBoot'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}
