// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function Author() {
  return window['go']['main']['App']['Author']();
}

export function LicenceText() {
  return window['go']['main']['App']['LicenceText']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function MarkRead(arg1, arg2) {
  return window['go']['main']['App']['MarkRead'](arg1, arg2);
}

export function OpenReleasesPage() {
  return window['go']['main']['App']['OpenReleasesPage']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SyncAccount(arg1) {
  return window['go']['main']['App']['SyncAccount'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
