// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function ApplyMeetingReply(arg1) {
  return window['go']['main']['App']['ApplyMeetingReply'](arg1);
}

export function Author() {
  return window['go']['main']['App']['Author']();
}

export function CancelOutboxItem(arg1) {
  return window['go']['main']['App']['CancelOutboxItem'](arg1);
}

export function ClearDraftRecovery() {
  return window['go']['main']['App']['ClearDraftRecovery']();
}

export function CopyMessage(arg1, arg2) {
  return window['go']['main']['App']['CopyMessage'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteCalendar(arg1) {
  return window['go']['main']['App']['DeleteCalendar'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteContactGroup(arg1) {
  return window['go']['main']['App']['DeleteContactGroup'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteEventScoped(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteEventScoped'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteMessagePermanent(arg1) {
  return window['go']['main']['App']['DeleteMessagePermanent'](arg1);
}

export function DeleteMessages(arg1) {
  return window['go']['main']['App']['DeleteMessages'](arg1);
}

export function DeleteMessagesPermanent(arg1) {
  return window['go']['main']['App']['DeleteMessagesPermanent'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DraftRecovery() {
  return window['go']['main']['App']['DraftRecovery']();
}

export function ExportContactsToFile(arg1) {
  return window['go']['main']['App']['ExportContactsToFile'](arg1);
}

export function ExportEventsToFile() {
  return window['go']['main']['App']['ExportEventsToFile']();
}

export function GetContact(arg1) {
  return window['go']['main']['App']['GetContact'](arg1);
}

export function GetEvent(arg1) {
  return window['go']['main']['App']['GetEvent'](arg1);
}

export function GetInvitation(arg1) {
  return window['go']['main']['App']['GetInvitation'](arg1);
}

export function GetMessageBody(arg1) {
  return window['go']['main']['App']['GetMessageBody'](arg1);
}

export function ImportContactsFromFile() {
  return window['go']['main']['App']['ImportContactsFromFile']();
}

export function ImportEventsFromFile() {
  return window['go']['main']['App']['ImportEventsFromFile']();
}

export function LicenceText() {
  return window['go']['main']['App']['LicenceText']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListCalendars() {
  return window['go']['main']['App']['ListCalendars']();
}

export function ListContactGroups() {
  return window['go']['main']['App']['ListContactGroups']();
}

export function ListContacts() {
  return window['go']['main']['App']['ListContacts']();
}

export function ListEventInstances(arg1, arg2) {
  return window['go']['main']['App']['ListEventInstances'](arg1, arg2);
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListOutbox() {
  return window['go']['main']['App']['ListOutbox']();
}

export function ListRules() {
  return window['go']['main']['App']['ListRules']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function ListThreads(arg1) {
  return window['go']['main']['App']['ListThreads'](arg1);
}

export function MarkFlagged(arg1, arg2) {
  return window['go']['main']['App']['MarkFlagged'](arg1, arg2);
}

export function MarkJunk(arg1) {
  return window['go']['main']['App']['MarkJunk'](arg1);
}

export function MarkRead(arg1, arg2) {
  return window['go']['main']['App']['MarkRead'](arg1, arg2);
}

export function MessageTags(arg1) {
  return window['go']['main']['App']['MessageTags'](arg1);
}

export function MinimiseToTray() {
  return window['go']['main']['App']['MinimiseToTray']();
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MoveMessage(arg1, arg2) {
  return window['go']['main']['App']['MoveMessage'](arg1, arg2);
}

export function MoveMessages(arg1, arg2) {
  return window['go']['main']['App']['MoveMessages'](arg1, arg2);
}

export function OpenAttachment(arg1, arg2) {
  return window['go']['main']['App']['OpenAttachment'](arg1, arg2);
}

export function OpenEmailAttachment(arg1, arg2) {
  return window['go']['main']['App']['OpenEmailAttachment'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenReleasesPage() {
  return window['go']['main']['App']['OpenReleasesPage']();
}

export function OutboxCount() {
  return window['go']['main']['App']['OutboxCount']();
}

export function PickAttachments() {
  return window['go']['main']['App']['PickAttachments']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RemoveCancelledMeeting(arg1) {
  return window['go']['main']['App']['RemoveCancelledMeeting'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function ReorderAccounts(arg1) {
  return window['go']['main']['App']['ReorderAccounts'](arg1);
}

export function ReplayOutbox() {
  return window['go']['main']['App']['ReplayOutbox']();
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function RespondToInvitation(arg1, arg2) {
  return window['go']['main']['App']['RespondToInvitation'](arg1, arg2);
}

export function SaveAllAttachments(arg1) {
  return window['go']['main']['App']['SaveAllAttachments'](arg1);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2);
}

export function SaveCalendar(arg1) {
  return window['go']['main']['App']['SaveCalendar'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['main']['App']['SaveContact'](arg1);
}

export function SaveContactGroup(arg1) {
  return window['go']['main']['App']['SaveContactGroup'](arg1);
}

export function SaveDraft(arg1) {
  return window['go']['main']['App']['SaveDraft'](arg1);
}

export function SaveDraftRecovery(arg1) {
  return window['go']['main']['App']['SaveDraftRecovery'](arg1);
}

export function SaveEvent(arg1) {
  return window['go']['main']['App']['SaveEvent'](arg1);
}

export function SaveEventScoped(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveEventScoped'](arg1, arg2, arg3);
}

export function SaveMessageAs(arg1, arg2) {
  return window['go']['main']['App']['SaveMessageAs'](arg1, arg2);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveTag(arg1) {
  return window['go']['main']['App']['SaveTag'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SendMeetingCancel(arg1, arg2) {
  return window['go']['main']['App']['SendMeetingCancel'](arg1, arg2);
}

export function SendMeetingRequest(arg1, arg2) {
  return window['go']['main']['App']['SendMeetingRequest'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetMessageTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMessageTag'](arg1, arg2, arg3);
}

export function ShowDefaultAppSettings() {
  return window['go']['main']['App']['ShowDefaultAppSettings']();
}

export function SignInMicrosoft(arg1) {
  return window['go']['main']['App']['SignInMicrosoft'](arg1);
}

export function SyncAccount(arg1) {
  return window['go']['main']['App']['SyncAccount'](arg1);
}

export function SyncFolder(arg1) {
  return window['go']['main']['App']['SyncFolder'](arg1);
}

export function UnreadCounts() {
  return window['go']['main']['App']['UnreadCounts']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}

export function UpdateAccountProfile(arg1) {
  return window['go']['main']['App']['UpdateAccountProfile'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
