// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<main.AboutDTO>;

export function AddAccount(arg1:main.AccountSetupRequest):Promise<void>;

export function ApplyMeetingReply(arg1:string):Promise<void>;

export function Author():Promise<string>;

export function CancelOutboxItem(arg1:string):Promise<void>;

export function ClearDraftRecovery():Promise<void>;

export function CopyMessage(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteCalendar(arg1:string):Promise<void>;

export function DeleteContact(arg1:string):Promise<void>;

export function DeleteContactGroup(arg1:string):Promise<void>;

export function DeleteEvent(arg1:string):Promise<void>;

export function DeleteEventScoped(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteMessagePermanent(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DraftRecovery():Promise<main.DraftRecoveryDTO>;

export function ExportContactsToFile(arg1:string):Promise<boolean>;

export function ExportEventsToFile():Promise<boolean>;

export function GetContact(arg1:string):Promise<main.ContactDTO>;

export function GetEvent(arg1:string):Promise<main.EventDTO>;

export function GetInvitation(arg1:string):Promise<main.InvitationDTO>;

export function GetMessageBody(arg1:string):Promise<main.MessageBodyDTO>;

export function ImportContactsFromFile():Promise<number>;

export function ImportEventsFromFile():Promise<number>;

export function LicenceText():Promise<string>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function ListCalendars():Promise<Array<main.CalendarDTO>>;

export function ListContactGroups():Promise<Array<main.ContactGroupDTO>>;

export function ListContacts():Promise<Array<main.ContactDTO>>;

export function ListEventInstances(arg1:string,arg2:string):Promise<Array<main.EventInstanceDTO>>;

export function ListEvents():Promise<Array<main.EventDTO>>;

export function ListFolders(arg1:string):Promise<Array<main.FolderDTO>>;

export function ListMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function ListOutbox():Promise<Array<main.OutboxItemDTO>>;

export function ListRules():Promise<Array<main.RuleDTO>>;

export function ListTags():Promise<Array<main.TagDTO>>;

export function MarkFlagged(arg1:string,arg2:boolean):Promise<void>;

export function MarkRead(arg1:string,arg2:boolean):Promise<void>;

export function MessageTags(arg1:string):Promise<Array<main.TagDTO>>;

export function MinimiseToTray():Promise<void>;

export function MoveMessage(arg1:string,arg2:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenReleasesPage():Promise<void>;

export function OutboxCount():Promise<number>;

export function PickAttachments():Promise<Array<string>>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveCancelledMeeting(arg1:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function ReplayOutbox():Promise<number>;

export function RequestQuit():Promise<void>;

export function RespondToInvitation(arg1:string,arg2:string):Promise<void>;

export function SaveCalendar(arg1:main.CalendarRequest):Promise<void>;

export function SaveContact(arg1:main.ContactRequest):Promise<void>;

export function SaveContactGroup(arg1:main.ContactGroupRequest):Promise<void>;

export function SaveDraft(arg1:main.ComposeRequest):Promise<void>;

export function SaveDraftRecovery(arg1:main.DraftRecoveryRequest):Promise<void>;

export function SaveEvent(arg1:main.EventRequest):Promise<string>;

export function SaveEventScoped(arg1:main.EventRequest,arg2:number,arg3:string):Promise<void>;

export function SaveMessageAs(arg1:string,arg2:string):Promise<void>;

export function SaveRule(arg1:main.RuleRequest):Promise<void>;

export function SaveTag(arg1:main.TagRequest):Promise<void>;

export function SearchMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function SendMeetingCancel(arg1:string,arg2:string):Promise<void>;

export function SendMeetingRequest(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:main.ComposeRequest):Promise<void>;

export function SetMessageTag(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SyncAccount(arg1:string):Promise<void>;

export function SyncFolder(arg1:string):Promise<void>;

export function UnreadCounts():Promise<main.UnreadCountsDTO>;

export function UpdateAccount(arg1:main.AccountSetupRequest):Promise<void>;

export function Version():Promise<string>;
