// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<main.AboutDTO>;

export function Author():Promise<string>;

export function LicenceText():Promise<string>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function ListFolders(arg1:string):Promise<Array<main.FolderDTO>>;

export function ListMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function MarkRead(arg1:string,arg2:boolean):Promise<void>;

export function OpenReleasesPage():Promise<void>;

export function SendMessage(arg1:main.ComposeRequest):Promise<void>;

export function SyncAccount(arg1:string):Promise<void>;

export function Version():Promise<string>;
