// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<main.AboutDTO>;

export function AddAccount(arg1:main.AccountSetupRequest):Promise<void>;

export function Author():Promise<string>;

export function CopyMessage(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function GetMessageBody(arg1:string):Promise<main.MessageBodyDTO>;

export function LicenceText():Promise<string>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function ListFolders(arg1:string):Promise<Array<main.FolderDTO>>;

export function ListMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function ListRules():Promise<Array<main.RuleDTO>>;

export function ListTags():Promise<Array<main.TagDTO>>;

export function MarkFlagged(arg1:string,arg2:boolean):Promise<void>;

export function MarkRead(arg1:string,arg2:boolean):Promise<void>;

export function MessageTags(arg1:string):Promise<Array<main.TagDTO>>;

export function MoveMessage(arg1:string,arg2:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenReleasesPage():Promise<void>;

export function OutboxCount():Promise<number>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function ReplayOutbox():Promise<number>;

export function SaveDraft(arg1:main.ComposeRequest):Promise<void>;

export function SaveRule(arg1:main.RuleRequest):Promise<void>;

export function SaveTag(arg1:main.TagRequest):Promise<void>;

export function SearchMessages(arg1:string):Promise<Array<main.MessageDTO>>;

export function SendMessage(arg1:main.ComposeRequest):Promise<void>;

export function SetMessageTag(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SyncAccount(arg1:string):Promise<void>;

export function UpdateAccount(arg1:main.AccountSetupRequest):Promise<void>;

export function Version():Promise<string>;
